### PR TITLE
maintain permission

### PR DESCRIPTION
**Pull request by zhangnaru0605**
set umask in case resolv.conf doesn't exist

### CODE REVIEW

**Comment by jamacku** [comment]
Thank you for your contribution. This patch make sense to me.
There is only one small thing, could you please change ``umask $oldumask`` to ``umask "$oldumask"``.
Thank you.

**Comment by zhangnaru0605** [comment]
> Thank you for your contribution. This patch make sense to me.
> There is only one small thing, could you please change `umask $oldumask` to `umask "$oldumask"`.
> Thank you.

**Comment by zhangnaru0605** [comment]
update maintain permission: change umask $oldumask to umask "$oldumask"

**Comment by jamacku** [comment]
Thank you.

**Comment by zhangnaru0605** [comment]
Hello, could you please review my commit again, due to my misoperation, the Review is requied, thank you!

**Comment by jamacku** [comment]
@zhangnaru0605, thank you for your contribution. Could you please squash your commits into one and force push it. Thank you.

**Comment by zhangnaru0605** [comment]
@jamacku , I will close this PR and commit new one ,thank you!

**Pull request closed without merging**
