### PR TITLE
Enable copr builds and add packit config

### PR DESCRIPTION
**Pull request by dhodovsk**
Let us introduce [packit service](https://packit.dev) to you - the automation to integrate upstream open source projects into Fedora operating system.

After merging this PR, you are just a few steps away from RPM builds being automatically triggered on your PR's.
It means, that you'll be able to try and play with your change, packaged as an RPM.

But there is more. By using packit, you can for example enable adding new releases into Fedora Rawhide.

What are the next steps?
* Install [Packit-as-a-Service github application](https://github.com/marketplace/packit-as-a-service) in your repo
* In case you are first user, wait for account approval
* Enjoy the built RPMs!

For more info, please:
 * check out the documentation: https://packit.dev/docs/
 * contact @packit-service

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Not sure if you have already installed the github app to the repo: https://github.com/marketplace/packit-as-a-service

Once you do, we can test the builds. I presume we need to tinker chroots since you probably need builds for `EL{7,8}`.

**Comment by jamacku** [comment]
> Not sure if you have already installed the github app to the repo: https://github.com/marketplace/packit-as-a-service
No we don't have, I'll have a look at it once I'll have a bit more time to play with it.

> Once you do, we can test the builds. I presume we need to tinker chroots since you probably need builds for `EL{7,8}`.
I'm not sure what you mean by that. There i master branch for Fedora and new features in general and separated branches for maintenance of RHEL7 and RHEL8

**Comment by TomasTomecek** [comment]
> > Not sure if you have already installed the github app to the repo: https://github.com/marketplace/packit-as-a-service
> 
> No we don't have, I'll have a look at it once I'll have a bit more time to play with it.

oki, please get in touch with us once you do and we'll help you; #packit on freenode & internal

**Comment by jamacku** [comment]
Thank you Tom, I'll get in touch with you soon.

**Comment by jamacku** [comment]
@dhodovsk @TomasTomecek , I created new PR could you please make a review #375 

Thanks
I'm closing this one.

**Pull request closed without merging**
