### PR TITLE
Backport #2 to rhel6-branch

### PR DESCRIPTION
**Pull request by jaymzh**
Completely backwards compatible.

### CODE REVIEW

**Comment by lnykryn** [comment]
In the future I would use is_false is_true everywhere, they are much more user-friendly. Beside that everything looks good to me.

But since we are pretty late in 6.9 development I will leave this to @deekej , if he wants to respin the initscripts release for 6.9.

**Comment by deekej** [comment]
I'm sorry, @jaymzh, I was engaged in other necessary stuff before, and now it's too late to make any changes to initscripts in RHEL-6.9 (the ''beta'' is already out). We can discuss the initscripts in RHEL6 more during DevConfCZ.17... ;)

**Comment by deekej** [comment]
It's too late to get this into RHEL-6.9. @jaymzh, I'm not sure this could make it into RHEL-6.10 (if there will be any RHEL-6.10). Would you mind if I close this PR?

**Comment by jaymzh** [comment]
Yeah it's fine. We'll be off of RHEL6 by then anyway. :)

**Pull request closed without merging**
